platform :ios, '13.0'

def shared_pods

  use_frameworks!
  pod 'SwiftGRPCDebugger', :path => '../'
  pod 'RxSwift'

end

target 'SwiftGRPCDebugger_Tests' do
  shared_pods
end

target 'example' do
  shared_pods
end
