//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: orders.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftProtobuf
import SwiftGRPCDebugger

internal protocol OrdersEventOrdersCreateCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersCreateCallBase: ClientCallUnaryBase<OrdersCreateReq, OrdersCreateResp>, OrdersEventOrdersCreateCall {
  override class var method: String { return "/tix.service.EventOrders/Create" }
}

internal protocol OrdersEventOrdersCancelCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersCancelCallBase: ClientCallUnaryBase<OrdersCancelReq, SwiftProtobuf.Google_Protobuf_Empty>, OrdersEventOrdersCancelCall {
  override class var method: String { return "/tix.service.EventOrders/Cancel" }
}

internal protocol OrdersEventOrdersCheckCreateStatusCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersCheckCreateStatusCallBase: ClientCallUnaryBase<OrdersCheckCreateStatusReq, OrdersCheckCreateStatusResp>, OrdersEventOrdersCheckCreateStatusCall {
  override class var method: String { return "/tix.service.EventOrders/CheckCreateStatus" }
}

internal protocol OrdersEventOrdersAdditionalInfoCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersAdditionalInfoCallBase: ClientCallUnaryBase<OrdersAdditionalInfoReq, SwiftProtobuf.Google_Protobuf_Empty>, OrdersEventOrdersAdditionalInfoCall {
  override class var method: String { return "/tix.service.EventOrders/AdditionalInfo" }
}

internal protocol OrdersEventOrdersCheckoutURLCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersCheckoutURLCallBase: ClientCallUnaryBase<OrdersCheckoutURLReq, OrdersCheckoutURLResp>, OrdersEventOrdersCheckoutURLCall {
  override class var method: String { return "/tix.service.EventOrders/CheckoutURL" }
}

internal protocol OrdersEventOrdersGetUpcomingOrderCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersGetUpcomingOrderCallBase: ClientCallUnaryBase<OrdersUpcomingOrderReq, OrdersUpcomingOrderResp>, OrdersEventOrdersGetUpcomingOrderCall {
  override class var method: String { return "/tix.service.EventOrders/GetUpcomingOrder" }
}

internal protocol OrdersEventOrdersGetTransactionOrderCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersGetTransactionOrderCallBase: ClientCallUnaryBase<OrdersTransactionOrderReq, OrdersTransactionOrderResp>, OrdersEventOrdersGetTransactionOrderCall {
  override class var method: String { return "/tix.service.EventOrders/GetTransactionOrder" }
}

internal protocol OrdersEventOrdersGetTicketDetailCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersGetTicketDetailCallBase: ClientCallUnaryBase<OrdersTicketDetailReq, OrdersTicketDetailResp>, OrdersEventOrdersGetTicketDetailCall {
  override class var method: String { return "/tix.service.EventOrders/GetTicketDetail" }
}

internal protocol OrdersEventOrdersCheckTicketStatusCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersCheckTicketStatusCallBase: ClientCallUnaryBase<OrdersTicketCheckingReq, OrdersTicketStatusResp>, OrdersEventOrdersCheckTicketStatusCall {
  override class var method: String { return "/tix.service.EventOrders/CheckTicketStatus" }
}

internal protocol OrdersEventOrdersChangeOrderReadStatusCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersChangeOrderReadStatusCallBase: ClientCallUnaryBase<OrdersOrderChangingReadStatusReq, OrdersOrderChangingReadStatusResp>, OrdersEventOrdersChangeOrderReadStatusCall {
  override class var method: String { return "/tix.service.EventOrders/ChangeOrderReadStatus" }
}


/// Instantiate OrdersEventOrdersServiceClient, then call methods of this protocol to make API calls.
internal protocol OrdersEventOrdersService: ServiceClient {
  /// Synchronous. Unary.
  func create(_ request: OrdersCreateReq) throws -> OrdersCreateResp
  /// Asynchronous. Unary.
  func create(_ request: OrdersCreateReq, completion: @escaping (OrdersCreateResp?, CallResult) -> Void) throws -> OrdersEventOrdersCreateCall

  /// Synchronous. Unary.
  func cancel(_ request: OrdersCancelReq) throws -> SwiftProtobuf.Google_Protobuf_Empty
  /// Asynchronous. Unary.
  func cancel(_ request: OrdersCancelReq, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> OrdersEventOrdersCancelCall

  /// Synchronous. Unary.
  func checkCreateStatus(_ request: OrdersCheckCreateStatusReq) throws -> OrdersCheckCreateStatusResp
  /// Asynchronous. Unary.
  func checkCreateStatus(_ request: OrdersCheckCreateStatusReq, completion: @escaping (OrdersCheckCreateStatusResp?, CallResult) -> Void) throws -> OrdersEventOrdersCheckCreateStatusCall

  /// Synchronous. Unary.
  func additionalInfo(_ request: OrdersAdditionalInfoReq) throws -> SwiftProtobuf.Google_Protobuf_Empty
  /// Asynchronous. Unary.
  func additionalInfo(_ request: OrdersAdditionalInfoReq, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> OrdersEventOrdersAdditionalInfoCall

  /// Synchronous. Unary.
  func checkoutURL(_ request: OrdersCheckoutURLReq) throws -> OrdersCheckoutURLResp
  /// Asynchronous. Unary.
  func checkoutURL(_ request: OrdersCheckoutURLReq, completion: @escaping (OrdersCheckoutURLResp?, CallResult) -> Void) throws -> OrdersEventOrdersCheckoutURLCall

  /// Synchronous. Unary.
  func getUpcomingOrder(_ request: OrdersUpcomingOrderReq) throws -> OrdersUpcomingOrderResp
  /// Asynchronous. Unary.
  func getUpcomingOrder(_ request: OrdersUpcomingOrderReq, completion: @escaping (OrdersUpcomingOrderResp?, CallResult) -> Void) throws -> OrdersEventOrdersGetUpcomingOrderCall

  /// Synchronous. Unary.
  func getTransactionOrder(_ request: OrdersTransactionOrderReq) throws -> OrdersTransactionOrderResp
  /// Asynchronous. Unary.
  func getTransactionOrder(_ request: OrdersTransactionOrderReq, completion: @escaping (OrdersTransactionOrderResp?, CallResult) -> Void) throws -> OrdersEventOrdersGetTransactionOrderCall

  /// Synchronous. Unary.
  func getTicketDetail(_ request: OrdersTicketDetailReq) throws -> OrdersTicketDetailResp
  /// Asynchronous. Unary.
  func getTicketDetail(_ request: OrdersTicketDetailReq, completion: @escaping (OrdersTicketDetailResp?, CallResult) -> Void) throws -> OrdersEventOrdersGetTicketDetailCall

  /// Synchronous. Unary.
  func checkTicketStatus(_ request: OrdersTicketCheckingReq) throws -> OrdersTicketStatusResp
  /// Asynchronous. Unary.
  func checkTicketStatus(_ request: OrdersTicketCheckingReq, completion: @escaping (OrdersTicketStatusResp?, CallResult) -> Void) throws -> OrdersEventOrdersCheckTicketStatusCall

  /// Synchronous. Unary.
  func changeOrderReadStatus(_ request: OrdersOrderChangingReadStatusReq) throws -> OrdersOrderChangingReadStatusResp
  /// Asynchronous. Unary.
  func changeOrderReadStatus(_ request: OrdersOrderChangingReadStatusReq, completion: @escaping (OrdersOrderChangingReadStatusResp?, CallResult) -> Void) throws -> OrdersEventOrdersChangeOrderReadStatusCall

}

internal final class OrdersEventOrdersServiceClient: ServiceClientBase, OrdersEventOrdersService {
  /// Synchronous. Unary.
  internal func create(_ request: OrdersCreateReq) throws -> OrdersCreateResp {
    return try OrdersEventOrdersCreateCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func create(_ request: OrdersCreateReq, completion: @escaping (OrdersCreateResp?, CallResult) -> Void) throws -> OrdersEventOrdersCreateCall {
    return try OrdersEventOrdersCreateCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func cancel(_ request: OrdersCancelReq) throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try OrdersEventOrdersCancelCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func cancel(_ request: OrdersCancelReq, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> OrdersEventOrdersCancelCall {
    return try OrdersEventOrdersCancelCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func checkCreateStatus(_ request: OrdersCheckCreateStatusReq) throws -> OrdersCheckCreateStatusResp {
    return try OrdersEventOrdersCheckCreateStatusCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func checkCreateStatus(_ request: OrdersCheckCreateStatusReq, completion: @escaping (OrdersCheckCreateStatusResp?, CallResult) -> Void) throws -> OrdersEventOrdersCheckCreateStatusCall {
    return try OrdersEventOrdersCheckCreateStatusCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func additionalInfo(_ request: OrdersAdditionalInfoReq) throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try OrdersEventOrdersAdditionalInfoCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func additionalInfo(_ request: OrdersAdditionalInfoReq, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> OrdersEventOrdersAdditionalInfoCall {
    return try OrdersEventOrdersAdditionalInfoCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func checkoutURL(_ request: OrdersCheckoutURLReq) throws -> OrdersCheckoutURLResp {
    return try OrdersEventOrdersCheckoutURLCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func checkoutURL(_ request: OrdersCheckoutURLReq, completion: @escaping (OrdersCheckoutURLResp?, CallResult) -> Void) throws -> OrdersEventOrdersCheckoutURLCall {
    return try OrdersEventOrdersCheckoutURLCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getUpcomingOrder(_ request: OrdersUpcomingOrderReq) throws -> OrdersUpcomingOrderResp {
    return try OrdersEventOrdersGetUpcomingOrderCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getUpcomingOrder(_ request: OrdersUpcomingOrderReq, completion: @escaping (OrdersUpcomingOrderResp?, CallResult) -> Void) throws -> OrdersEventOrdersGetUpcomingOrderCall {
    return try OrdersEventOrdersGetUpcomingOrderCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getTransactionOrder(_ request: OrdersTransactionOrderReq) throws -> OrdersTransactionOrderResp {
    return try OrdersEventOrdersGetTransactionOrderCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getTransactionOrder(_ request: OrdersTransactionOrderReq, completion: @escaping (OrdersTransactionOrderResp?, CallResult) -> Void) throws -> OrdersEventOrdersGetTransactionOrderCall {
    return try OrdersEventOrdersGetTransactionOrderCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getTicketDetail(_ request: OrdersTicketDetailReq) throws -> OrdersTicketDetailResp {
    return try OrdersEventOrdersGetTicketDetailCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getTicketDetail(_ request: OrdersTicketDetailReq, completion: @escaping (OrdersTicketDetailResp?, CallResult) -> Void) throws -> OrdersEventOrdersGetTicketDetailCall {
    return try OrdersEventOrdersGetTicketDetailCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func checkTicketStatus(_ request: OrdersTicketCheckingReq) throws -> OrdersTicketStatusResp {
    return try OrdersEventOrdersCheckTicketStatusCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func checkTicketStatus(_ request: OrdersTicketCheckingReq, completion: @escaping (OrdersTicketStatusResp?, CallResult) -> Void) throws -> OrdersEventOrdersCheckTicketStatusCall {
    return try OrdersEventOrdersCheckTicketStatusCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func changeOrderReadStatus(_ request: OrdersOrderChangingReadStatusReq) throws -> OrdersOrderChangingReadStatusResp {
    return try OrdersEventOrdersChangeOrderReadStatusCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func changeOrderReadStatus(_ request: OrdersOrderChangingReadStatusReq, completion: @escaping (OrdersOrderChangingReadStatusResp?, CallResult) -> Void) throws -> OrdersEventOrdersChangeOrderReadStatusCall {
    return try OrdersEventOrdersChangeOrderReadStatusCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}
internal protocol OrdersEventOrdersInternalManualRefundCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersInternalManualRefundCallBase: ClientCallUnaryBase<OrdersManualRefundReq, SwiftProtobuf.Google_Protobuf_Empty>, OrdersEventOrdersInternalManualRefundCall {
  override class var method: String { return "/tix.service.EventOrdersInternal/ManualRefund" }
}

internal protocol OrdersEventOrdersInternalManualCancelCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersInternalManualCancelCallBase: ClientCallUnaryBase<OrdersManualCancelReq, SwiftProtobuf.Google_Protobuf_Empty>, OrdersEventOrdersInternalManualCancelCall {
  override class var method: String { return "/tix.service.EventOrdersInternal/ManualCancel" }
}

internal protocol OrdersEventOrdersInternalQueryTransactionCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersInternalQueryTransactionCallBase: ClientCallUnaryBase<OrdersQueryTransactionReq, OrdersQueryTransactionResp>, OrdersEventOrdersInternalQueryTransactionCall {
  override class var method: String { return "/tix.service.EventOrdersInternal/QueryTransaction" }
}

internal protocol OrdersEventOrdersInternalChangeOrderEmailCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersInternalChangeOrderEmailCallBase: ClientCallUnaryBase<OrdersChangeOrderEmailReq, SwiftProtobuf.Google_Protobuf_Empty>, OrdersEventOrdersInternalChangeOrderEmailCall {
  override class var method: String { return "/tix.service.EventOrdersInternal/ChangeOrderEmail" }
}

internal protocol OrdersEventOrdersInternalResendOrderEmailCall: ClientCallUnary {}

fileprivate final class OrdersEventOrdersInternalResendOrderEmailCallBase: ClientCallUnaryBase<OrdersResendOrderEmailReq, SwiftProtobuf.Google_Protobuf_Empty>, OrdersEventOrdersInternalResendOrderEmailCall {
  override class var method: String { return "/tix.service.EventOrdersInternal/ResendOrderEmail" }
}


/// Instantiate OrdersEventOrdersInternalServiceClient, then call methods of this protocol to make API calls.
internal protocol OrdersEventOrdersInternalService: ServiceClient {
  /// Synchronous. Unary.
  func manualRefund(_ request: OrdersManualRefundReq) throws -> SwiftProtobuf.Google_Protobuf_Empty
  /// Asynchronous. Unary.
  func manualRefund(_ request: OrdersManualRefundReq, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> OrdersEventOrdersInternalManualRefundCall

  /// Synchronous. Unary.
  func manualCancel(_ request: OrdersManualCancelReq) throws -> SwiftProtobuf.Google_Protobuf_Empty
  /// Asynchronous. Unary.
  func manualCancel(_ request: OrdersManualCancelReq, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> OrdersEventOrdersInternalManualCancelCall

  /// Synchronous. Unary.
  func queryTransaction(_ request: OrdersQueryTransactionReq) throws -> OrdersQueryTransactionResp
  /// Asynchronous. Unary.
  func queryTransaction(_ request: OrdersQueryTransactionReq, completion: @escaping (OrdersQueryTransactionResp?, CallResult) -> Void) throws -> OrdersEventOrdersInternalQueryTransactionCall

  /// Synchronous. Unary.
  func changeOrderEmail(_ request: OrdersChangeOrderEmailReq) throws -> SwiftProtobuf.Google_Protobuf_Empty
  /// Asynchronous. Unary.
  func changeOrderEmail(_ request: OrdersChangeOrderEmailReq, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> OrdersEventOrdersInternalChangeOrderEmailCall

  /// Synchronous. Unary.
  func resendOrderEmail(_ request: OrdersResendOrderEmailReq) throws -> SwiftProtobuf.Google_Protobuf_Empty
  /// Asynchronous. Unary.
  func resendOrderEmail(_ request: OrdersResendOrderEmailReq, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> OrdersEventOrdersInternalResendOrderEmailCall

}

internal final class OrdersEventOrdersInternalServiceClient: ServiceClientBase, OrdersEventOrdersInternalService {
  /// Synchronous. Unary.
  internal func manualRefund(_ request: OrdersManualRefundReq) throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try OrdersEventOrdersInternalManualRefundCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func manualRefund(_ request: OrdersManualRefundReq, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> OrdersEventOrdersInternalManualRefundCall {
    return try OrdersEventOrdersInternalManualRefundCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func manualCancel(_ request: OrdersManualCancelReq) throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try OrdersEventOrdersInternalManualCancelCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func manualCancel(_ request: OrdersManualCancelReq, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> OrdersEventOrdersInternalManualCancelCall {
    return try OrdersEventOrdersInternalManualCancelCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func queryTransaction(_ request: OrdersQueryTransactionReq) throws -> OrdersQueryTransactionResp {
    return try OrdersEventOrdersInternalQueryTransactionCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func queryTransaction(_ request: OrdersQueryTransactionReq, completion: @escaping (OrdersQueryTransactionResp?, CallResult) -> Void) throws -> OrdersEventOrdersInternalQueryTransactionCall {
    return try OrdersEventOrdersInternalQueryTransactionCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func changeOrderEmail(_ request: OrdersChangeOrderEmailReq) throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try OrdersEventOrdersInternalChangeOrderEmailCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func changeOrderEmail(_ request: OrdersChangeOrderEmailReq, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> OrdersEventOrdersInternalChangeOrderEmailCall {
    return try OrdersEventOrdersInternalChangeOrderEmailCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func resendOrderEmail(_ request: OrdersResendOrderEmailReq) throws -> SwiftProtobuf.Google_Protobuf_Empty {
    return try OrdersEventOrdersInternalResendOrderEmailCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func resendOrderEmail(_ request: OrdersResendOrderEmailReq, completion: @escaping (SwiftProtobuf.Google_Protobuf_Empty?, CallResult) -> Void) throws -> OrdersEventOrdersInternalResendOrderEmailCall {
    return try OrdersEventOrdersInternalResendOrderEmailCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

